📦 Move to ESM only
executablebooks/markdown-it-myst-extras pull request #2
Opened 2023-09-21 03:39 UTC by rowanc1

- vitest instead of jest
- update dependencies (open peer deps)
- simplify and update GitHub action

Maintains `requirejs` bundles to be used in the browser.
No code changes.

2023-09-21 03:51 UTC, rowanc1 commented
@chrisjsewell there are three PRs on these markdown-it repos that need to be fixed up, no code changes -- just changes to packaging. These move to ESM only, which is now more useful than a year ago; the current mix of CJS/ESM is breaking imports in various use cases.

The PRs are:
- https://github.com/executablebooks/markdown-it-myst-extras/pull/2
- https://github.com/executablebooks/markdown-it-dollarmath/pull/11
- https://github.com/executablebooks/markdown-it-amsmath/pull/10

They are all the same, following the [instructions here](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c), I left the rollup browser builds untouched. Let me know if you have any thoughts on these, if not, I can move ahead with minor (?) releases for each package.

2023-09-25 20:44 UTC, fwkoch approved these changes
This is nice - seems inevitable to update! (And anything that relies on cjs can just pin the old version for now since there are no code changes.)

2023-09-25 20:49 UTC, chrisjsewell requested changes

2023-09-25 20:49 UTC, chrisjsewell commented on README.md
> -### Why Jest?
Can you replace this with a brief explanation of why vitest cheers

2023-09-25 20:50 UTC, rowanc1 commented on README.md
> -### Why Jest?
Yep, sounds good. Basically exactly the same as jest, but works with ESM/typescript and runs 10x faster.

2023-09-25 20:53 UTC, chrisjsewell commented
No issues in principle cheers, yeh just if you can add the why vitest (and mention the difference to jest)

Sure you don't wanna move to using bun 😉 that's what the cool kids are doing lol

2023-09-25 21:21 UTC, rowanc1 commented
@chrisjsewell do you want to release these or shall I take them forward? Any preference on a patch/minor/major release?

2023-09-26 16:29 UTC, rowanc1 commented
@chrisjsewell I am planning to release these three repos in a few hours with a minor release to unblock some downstream work.

2023-09-26 21:35 UTC, merged